### ISSUE TITLE
change the interface in tcpdump master bash 

### ISSUE THREAD

**Issue by Julianlee75** [konsolebox/scripts#2]
Good Day! Sir,

Can you please help me? My server has interface ens33 but when I activate the code, the tcpdump is monitoring bluetooth device and I am not able to change it.

Can you please assist me

**Comment by konsolebox** [comment]
Try modifying `TCPDUMP_ARGS`'s assignment to `TCPDUMP_ARGS=(-C 1 -i ens33)` in the script.

**Comment by Julianlee75** [comment]
Hi Sir,

Is working! Thanks you very much
